# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:10:43+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    CocerCertificatePostRequest,
    CocerCertificatePostResponse,
    CocerCertificatePostResponse1,
    CocerCertificatePostResponse2,
    CocerCertificatePostResponse3,
    CocerCertificatePostResponse4,
    CocerCertificatePostResponse5,
    CocerCertificatePostResponse6,
    RfcerCertificatePostRequest,
    RfcerCertificatePostResponse,
    RfcerCertificatePostResponse1,
    RfcerCertificatePostResponse2,
    RfcerCertificatePostResponse3,
    RfcerCertificatePostResponse4,
    RfcerCertificatePostResponse5,
    RfcerCertificatePostResponse6,
)

app = MCPProxy(
    description='eSigned certificates issued by Department of Information Technology, Biotechnology and Science &Technology (http://itbt.karnataka.gov.in/pages/home.aspx) can be downloaded through DigiLocker.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Department of IT and BT, Karnataka',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/ktech/v3'}],
)


@app.post(
    '/cocer/certificate',
    description=""" API to verify Company Related Certificate. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def cocer(body: CocerCertificatePostRequest = None):
    """
    Company Related Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/rfcer/certificate',
    description=""" API to verify Registration Certificate of Firm/ Company. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def rfcer(body: RfcerCertificatePostRequest = None):
    """
    Registration Certificate of Firm/ Company
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
